### ISSUE TITLE
I'm participating

### ISSUE THREAD

**Issue by barbeque** [dariusk/wordnik-hackathon#6]
I got started a little early because I can't help myself.

Here's what I've done so far, using just synonyms and some cleverness:

Original:

> This stuff is the worst thing that I have ever seen and I want to really get rid of whoever came up with that stuff. Please ban this sick filth. Sincerely, Steve Buscemi.

Twisted:

> This cram is the discomfit appurtenances so M'Ass exact once versed together with My Ass need a royally have destroy a whoever came standing plus yon stuff. Please dit this weak filth. Sincerely, Steve Buscemi.

https://github.com/barbeque/well-actually

**Comment by dariusk** [comment]
Hahaha, excellent!

**Comment by mrjf** [comment]
Now this makes sense :)  

![image](https://cloud.githubusercontent.com/assets/180956/4963255/43f30230-6703-11e4-9404-2b5960cdcb70.png)
